repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
    args: ['--maxkb=10000']
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
    args: ['--unsafe']
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args: ['--fix=auto']

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    args: ["--line-length=120"]

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
